routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts',\App\Http\Controllers\ContactController::class);

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'birthdate',
        'address',
        'image_name'
    ];

    public function email()
    {
        return $this->hasMany(Email::class);
    }

    public function phone()
    {
        return $this->hasMany(Phone::class);
    }

    public function deleteImage() {
        Storage::delete($this->image_name);
    }

    public function scopeSearch($query)
    {
        $search = request('search');
        if($search)
        {
            return $query->where('first_name', 'like', "%$search%")
                    ->orWhere('last_name', 'like', "%$search%")
                    ->orWhereHas('email', function ($emailQuery) use ($search) {
                        $emailQuery->where('email', 'like', "%$search%");
                    })
                    ->orWhereHas('phone', function ($phoneQuery) use ($search) {
                        $phoneQuery->where('telephone', 'like', "%$search%");
                    })
                    ->orWhere('birthdate', 'like', "%$search%")
                    ->orWhere('address', 'like', "%$search%");
        }
        return $query;
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Phone;
use App\Models\Email;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::with('phone','email')->search()->paginate(12);
        return view('contacts.index',compact(['contacts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $phones = Phone::all();
        $emails = Email::all();
        return view('contacts.create',compact(['phones','emails']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = $request->file('image_name')->store('contacts');
        $contact = Contact::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'birthdate' => $request->birthdate,
            'address' => $request->address,
            'image_name' => $image,
        ]);

        $emails = $request->emails;
        foreach($emails as $email) {
            $isPrimary = ($email === $request->selected_email) ? 1 : 0;
            $contact->email()->create(['email' => $email, 'is_primary' => $isPrimary]);
        }

        $phones = $request->telephones;
        foreach($phones as $phone) {
            $isPrimary = ($phone === $request->selected_telephone) ? 1 : 0;
            $contact->phone()->create(['telephone' => $phone, 'is_primary' => $isPrimary]);
        }

        return redirect(route('contacts.index'))
            ->with([
                'status' => 'success',
                'message' => 'Contact Added Successfully!'
            ]
        );
    }

    /**
     * Display the specified resource.s
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        $phones = Phone::all();
        $emails = Email::all();
        return view('contacts.edit', compact(['contact','phones','emails']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        $data = $request->all();

        if($request->hasFile('image_name')) {
            $image = $request->file('image_name')->store('contacts');
            $data['image_name'] = $image;
            $contact->deleteImage();
        }

        $emails = $request->emails;
        $contact->email()->update(['is_primary' => '0']);
        foreach ($emails as $emailIndex => $newEmail) {
            $emailExist = $contact->email->get($emailIndex);
            if ($emailExist) {
                $emailExist->email = $newEmail;
                $emailExist->where('email', $request->selected_email)->update(['is_primary' => '1']);
                $emailExist->save();
            } else {
                $contact->email()->create(['email' => $newEmail]);
            }
            $contact->email()->where('email', $request->selected_email)->update(['is_primary' => '1']);
        }

        $phones = $request->telephones;
        $contact->phone()->update(['is_primary' => '0']);
        foreach ($phones as $phoneIndex => $newPhone) {
            $phoneExist = $contact->phone->get($phoneIndex);
            if ($phoneExist) {
                $phoneExist->telephone = $newPhone;
                $phoneExist->where('telephone', $request->selected_telephone)->update(['is_primary' => '1']);
                $phoneExist->save();
            } else {
                $contact->phone()->create(['telephone' => $newPhone]);
            }
            $contact->phone()->where('telephone', $request->selected_telephone)->update(['is_primary' => '1']);
        }

        $removedEmails = $contact->email->whereNotIn('email', $emails);
        foreach ($removedEmails as $removedEmail) {
            $removedEmail->delete();
        }

        $removedPhones = $contact->phone->whereNotIn('telephone', $phones);
        foreach ($removedPhones as $removedPhone) {
            $removedPhone->delete();
        }

        $contact->update($data);

        return redirect(route('contacts.index'))
            ->with([
                'status' => 'success',
                'message' => 'Contact Updated Successfully!'
            ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        $contact->deleteImage();
        return redirect(route('contacts.index'))->with(
            [
                'status' => 'success',
                'message' => 'Contact Deleted Successfully!'
            ]
        );
    }
}

resources/views/contacts/create.blade.php
@extends('contacts.layouts.app')

@section('title', 'Add Contact - By Udhay Chugh')

@section('main-content')
    <div class="container">
        <div class="row mt50 text-primary">
            <h2>Add New Contact</h2>
        </div>
        <div class="row">
            <form class="col s12 formValidate" action="{{ route("contacts.store") }}" id="add-contact-form" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row mb10">
                    <div class="input-field col s6">
                        <input id="first_name" name="first_name" type="text" class="validate" data-error=".first_name_error">
                        <label for="first_name">First Name</label>
                        <div class="first_name_error "></div>
                    </div>
                    <div class="input-field col s6">
                        <input id="last_name" name="last_name" type="text" class="validate" data-error=".last_name_error">
                        <label for="last_name">Last Name</label>
                        <div class="last_name_error "></div>
                    </div>
                </div>
                <div class="row mb10">
                    <div class="input-field col s05">
                        <label><input id="radio" class="with-gap" name="selected_email" type="radio" checked><span></span></label>
                    </div>
                    <div class="input-field col s40">
                        <input id="email" name="emails[]" type="email" class="validate" data-error=".email_error">
                        <label for="email">Email</label>
                        <div class="email_error "></div>
                    </div>
                    <div class="input-field col s05">
                        <button id="add_email" class="btn-floating btn-medium waves-effect waves-light blue" type="button"><i class="material-icons">add</i></button>
                    </div>
                    <div class="input-field col s6">
                        <input id="birthdate" name="birthdate" type="text" class="datepicker" data-error=".birthday_error">
                        <label for="birthdate">Birthdate</label>
                        <div class="birthday_error "></div>
                    </div>
                </div>
                <div class="mailwrapper"></div>
                <div class="row mb10">
                    <div class="input-field col s05">
                        <label><input id="radio" class="with-gap" name="selected_telephone" type="radio" checked/><span></span></label>
                    </div>
                    <div class="input-field col s90">
                        <input id="telephone" name="telephones[]" type="tel" class="validate" data-error=".telephone_error">
                        <label for="telephone">Telephone</label>
                        <div class="telephone_error "></div>
                    </div>
                    <div class="input-field col s05">
                        <button id="add_phone" class="btn-floating btn-medium waves-effect waves-light blue" type="button"><i class="material-icons">add</i></button>
                    </div>
                </div>
                <div class="telewrapper"></div>
                <div class="row mb10">
                    <div class="input-field col s12">
                        <textarea id="address" name="address" class="materialize-textarea" data-error=".address_error"></textarea>
                        <label for="address">Address</label>
                        <div class="address_error "></div>
                    </div>
                </div>
                <div class="row mb10">
                    <div class="file-field input-field col s12">
                        <div class="col s3">
                            <img class="circle" id="temp_image" >
                        </div>
                        <div class="btn btn-primary">
                            <span>Image</span>
                            <input type="file" name="image_name" id="pic" data-error=".pic_error">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Upload Your Image">
                        </div>
                        <div class="pic_error "></div>
                    </div>
                </div>
                <button id="submit" class="btn btn-primary waves-effect waves-light right px-3 py-1" type="submit" name="action">Submit
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src={{ asset("js/vendors/jquery-validation/validation.min.js") }} type="text/javascript"></script>
    <script src={{ asset("js/vendors/jquery-validation/additional-methods.min.js") }} type="text/javascript"></script>
    <script src={{ asset("js/pages/add-contact.js") }}></script>
    <script src={{ asset("js/pages/home.js") }}></script>
@endsection

resources/views/contacts/edit.blade.php
@extends('contacts.layouts.app')

@section('title', 'Edit Contact - By Udhay Chugh')

@section('main-content')
    <div class="container">
        <div class="row mt50 text-primary">
            <h2>Edit Old Contact</h2>
        </div>
        <div class="row">
            <form class="col s12 formValidate" action="{{ route("contacts.update", $contact) }}" id="update-contact-form" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row mb10">
                    <div class="input-field col s6">
                        <input id="first_name" name="first_name" type="text" class="validate" data-error=".first_name_error" value="{{ $contact->first_name }}">
                        <label for="first_name">First Name</label>
                        <div class="first_name_error "></div>
                    </div>
                    <div class="input-field col s6">
                        <input id="last_name" name="last_name" type="text" class="validate" data-error=".last_name_error" value="{{ $contact->last_name }}">
                        <label for="last_name">Last Name</label>
                        <div class="last_name_error "></div>
                    </div>
                </div>
                <div class="row mb10">
                    <div class="input-field col s05">
                        <label><input id="radio" class="with-gap" name="selected_email" type="radio"><span></span></label>
                    </div>
                    <div class="input-field col s40">
                        <input id="email" name="emails[]" type="email" class="validate" data-error=".email_error" value="{{ $contact->email->pluck('is_primary', 'email') }}">
                        <label for="email">Email</label>
                        <div class="email_error "></div>
                    </div>
                    <div class="input-field col s05">
                        <button id="add_email" class="btn-floating btn-medium waves-effect waves-light blue" type="button"><i class="material-icons">add</i></button>
                    </div>
                    <div class="input-field col s6">
                        <input id="birthdate" name="birthdate" type="text" class="datepicker" data-error=".birthday_error" value="{{ $contact->birthdate }}">
                        <label for="birthdate">Birthdate</label>
                        <div class="birthday_error "></div>
                    </div>
                </div>
                <div class="mailwrapper"></div>
                <div class="row mb10">
                    <div class="input-field col s05">
                        <label><input id="radio" class="with-gap" name="selected_telephone" type="radio"/><span></span></label>
                    </div>
                    <div class="input-field col s90">
                        <input id="telephone" name="telephones[]" type="tel" class="validate" data-error=".telephone_error" value="{{ $contact->phone->pluck('is_primary', 'telephone') }}">
                        <label for="telephone">Telephone</label>
                        <div class="telephone_error "></div>
                    </div>
                    <div class="input-field col s05">
                        <button id="add_phone" class="btn-floating btn-medium waves-effect waves-light blue" type="button"><i class="material-icons">add</i></button>
                    </div>
                </div>
                <div class="telewrapper"></div>
                <div class="row mb10">
                    <div class="input-field col s12">
                        <textarea id="address" name="address" class="materialize-textarea" data-error=".address_error">{{ $contact->address }}</textarea>
                        <label for="address">Address</label>
                        <div class="address_error "></div>
                    </div>
                </div>
                <div class="row mb10">
                    <div class="file-field input-field col s12">
                        <div class="col s3">
                            <img class="circle " id="temp_image" src="{{ asset("storage/$contact->image_name") }}" >
                        </div>
                        <div class="btn btn-primary">
                            <span>Image</span>
                            <input type="file" name="image_name" id="pic" data-error=".pic_error">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" placeholder="Upload Your Image" value="{{ trim($contact->image_name, "contacts/");}}">
                        </div>
                        <div class="pic_error "></div>
                    </div>
                </div>
                <button class="btn btn-primary waves-effect waves-light right px-3 py-1" type="submit" name="action">Update
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src={{ asset("js/vendors/jquery-validation/validation.min.js") }} type="text/javascript"></script>
    <script src={{ asset("js/vendors/jquery-validation/additional-methods.min.js") }} type="text/javascript"></script>
    <script src={{ asset("js/pages/update-contact.js") }}></script>
    <script src={{ asset("js/pages/home.js") }}
@endsection

resources/views/contacts/index.blade.php
@extends('contacts.layouts.app')

@section('title', 'Contact Management - By Udhay Chugh')

@section('main-content')
    <a href="{{ route('contacts.create') }}" class="btn btn-primary px-3 py-0 mx-2" type="submit">Add Contact <i class="fa fa-plus"></i></a>
    <a href="#" class="btn btn-outline-primary px-3 py-0 search" type="submit"><i class="fa fa-filter"></i> Filter</a>
    <div class="wrapper mt-3 mb-0"></div>
    <div class="d-grid m-1 cards">
        @foreach ($contacts as $contact)
            <div class="card m-1 cardSize position-relative">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="left">
                            <h5 class="card-text fw-bold">Name: {{ $contact->first_name." ".$contact->last_name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Email: {{ $contact->email->where('is_primary', 1)->pluck('email')->first() }}</h6>
                            <p class="card-text mb-2">Phone: {{ $contact->phone->where('is_primary', 1)->pluck('telephone')->first() }}</p>
                            <h6 class="card-subtitle mb-2">DOB: {{ $contact->birthdate }}</h6>
                            <p class="card-text text-muted m-0">Address: {{ $contact->address }}</p>
                        </div>
                        <div class="right m-auto mt-0">
                            <img src="{{ asset("storage/$contact->image_name") }}" class="circle" alt="..." height="60%" >
                        </div>
                    </div>
                    <div class="pt-4">
                        <a href={{ route('contacts.edit', $contact) }} class="btn btn-outline-secondary px-3 py-0" type="submit">Edit <i class="fa fa-pencil-square-o"></i></a>
                        <button href="#deleteModal" class="btn btn-outline-danger px-3 py-0 modal-trigger delete" data-bs-toggle="modal" data-bs-target="#deleteModal" data-contact-id="{{ $contact->id }}" type="submit" >Delete <i class="fa fa-trash-o"></i></button>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    {{ $contacts->appends(['search'=>request('search')])->links('contacts.layouts.partials._pagination') }}
@endsection

@section('modal')
    <div id="deleteModal" class="modal">
        <div class="modal-content">
            <h4>Delete Contact</h4>
            <p>Are you sure you want to delete the contact?</p>
        </div>
        <div class="modal-footer">
            <form id="deleteForm" method="POST">
                @csrf
                @method('DELETE')
                <a type="button" class="modal-close btn btn-secondary waves-effect">Cancel</a>
                <button type="submit" class="modal-close btn btn-danger waves-effect">Yes, Delete</button>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        document.querySelectorAll('.delete').forEach(function(btn){
            btn.addEventListener('click',handleDeleteClick);
        });

        function handleDeleteClick(evt){
            console.log(evt.target.dataset.contactId);
            const contactId = evt.target.dataset.contactId;
            const URL = `/contacts/${contactId}`;
            console.log(URL);
            document.getElementById('deleteForm').setAttribute('action',URL)
        }
    </script>
@endsection